### ISSUE TITLE
Request for Llama3.1 8B, 70B and 405B

### ISSUE THREAD

**Issue by RodriMora** [TIGER-AI-Lab/MMLU-Pro#10]
Hi!

Title is pretty much explanatory, vLLM now correctly supports the models since 0.5.3post1 and the tokenizer [has been fixed](https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct/discussions/9)

Could the new Llama3.1 models be added to the leaderboard? I could only provide the results for the 8B, I don't have the resources for 70B and 405B unquantized models.

There seems to be another PR pending for the llama3.1 models but it's related to the tool calling so I don't think it would affect the results ( https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct/discussions/12 )

Thanks!

**Comment by Wyyyb** [comment]
Thank you for the suggestion and the update on the support for vLLM models and tokenizer fixes. Regarding adding the new Llama3.1 models to the leaderboard, the 8B and 8B Instruct versions are already in progress. We are also planning to run the 70B and 70B Instruct models soon.

**Comment by wenhuchen** [comment]
It's added now. Thanks!

**Comment by RodriMora** [comment]
Did you used the updated model with the fixed tokenizer?

I'm getting a bit better results:

Llama3.1-8B-Instruct

| overall | biology | business | chemistry | computer science | economics | engineering | health | history | law | math | philosophy | physics | psychology | other |
| ------- | ------- | -------- | --------- | ---------------- | --------- | ----------- | ------ | ------- | --- | ---- | ---------- | ------- | ---------- | ----- |
| 48.28 | 65.41 | 56.27 | 40.37 | 49.51 | 59.72 | 32.61 | 56.60 | 43.83 | 33.79 | 50.11 | 44.49 | 42.88 | 62.66 | 49.57 |


vs

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/a3ae18a2-7cc4-4444-9100-c335a853b526">

**Comment by Wyyyb** [comment]
If you are referring to the update to chat_template in tokenizer_config.json on July 30th, the answer is no. Thank you for the reminder; we will re-evaluate using the updated tokenizer today.

**Comment by Wyyyb** [comment]
We just re-evaluated using the updated tokenizer, and the results showed very minimal fluctuations. Did you obtain your results using the code from our Git repository? If not, are there any settings that differ from ours?
