### ISSUE TITLE
Add Grok-2?

### ISSUE THREAD

**Issue by mrconter1** [TIGER-AI-Lab/MMLU-Pro#12]
Is it possible to add the results for Grok-2 on this to the leaderboard?

> https://x.ai/blog/grok-2

Best regards

**Comment by wenhuchen** [comment]
We are asking them for the breakdown now. We will update once we receive that.

**Comment by EwoutH** [comment]
They now have an official API:

https://docs.x.ai/docs | https://docs.x.ai/api

It would be great to have full, validated numbers on Grok 2. Some recent first-party numbers where exaggerated.
