### ISSUE TITLE
Add Qwen2.5 model family

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#22]
Tracking issue for the Qwen2.5 model family. These models are SOTA in their sizes on many benchmarks, and most are released under an permissive Apache 2.0 license.

Models on HuggingFace: [Qwen2.5](https://huggingface.co/collections/Qwen/qwen25-66e81a666513e518adb90d9e) | [Qwen2.5-Coder](https://huggingface.co/collections/Qwen/qwen25-coder-66eaa22e6f99801bf65b0c2f) | [Qwen2.5-Math](https://huggingface.co/collections/Qwen/qwen25-math-66eaa240a1b7d5ee65f1da3e).

There are a lot of model in total, but I would add (at least):
- [Qwen/Qwen2.5-7B](https://huggingface.co/Qwen/Qwen2.5-7B)
- [Qwen/Qwen2.5-32B](https://huggingface.co/Qwen/Qwen2.5-32B) (largest Apache 2.0 model)
- [Qwen/Qwen2.5-72B](https://huggingface.co/Qwen/Qwen2.5-72B)
- [Qwen/Qwen2.5-Coder-1.5B](https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B)
- [Qwen/Qwen2.5-Coder-7B](https://huggingface.co/Qwen/Qwen2.5-Coder-7B)
- [Qwen/Qwen2.5-Math-7B](https://huggingface.co/Qwen/Qwen2.5-Math-7B)
- [Qwen/Qwen2.5-Math-72B](https://huggingface.co/Qwen/Qwen2.5-Math-72B)
- [Qwen/Qwen2.5-Math-RM-72B](https://huggingface.co/Qwen/Qwen2.5-Math-RM-72B)

There are also instruct-tuned models available for most models.

**Comment by ubergarm** [comment]
Some benchmarks are showing up for various quants already using [chigkim/Ollama-MMLU-Pro]](https://github.com/chigkim/Ollama-MMLU-Pro) posted on [this reddit sub r/LocalLLaMA thread](https://www.reddit.com/r/LocalLLaMA/comments/1fkm5vd/qwen25_32b_gguf_evaluation_results/). 

Looks promising so far...

**Comment by Wyyyb** [comment]
Thank you for your suggestions. We have updated the evaluation results for the Qwen2.5 series models in the leaderboard.

**Comment by ubergarm** [comment]
Just to save future folks a few clicks, the leaderboard is here: https://huggingface.co/spaces/TIGER-Lab/MMLU-Pro

**Comment by EwoutH** [comment]
> We have updated the evaluation results for the Qwen2.5 series models in the leaderboard.

Awesome! I saw the results are self-reported, are you planning on validating (one or more of) the Qwen2.5 models?
