### ISSUE TITLE
Suggested minimum context length requirement?

### ISSUE THREAD

**Issue by ubergarm** [TIGER-AI-Lab/MMLU-Pro#23]
I know all models use various token encodings, but in a cursory search I didn't see specific context length used for testing local LLMs e.g. is a `ctx_length` of 1024 enough?

I guess I could look at the length of the largest text blob and convert that to tokens for the model of interest, but curious if there was an already documented guidance here that I missed?

The reason I ask, is if I use 8k ctx then I have less VRAM for offloading from llama.cpp vs say 1k ctx. It can make the difference in a few tok/sec which would speed up benchmarking enough to make it worthwhile to me.

Cheers and feel free to ignore and close if not!

**Comment by Wyyyb** [comment]
Thank you for your question. We recommend using a context length of 4096 tokens. This can be found in our code at https://github.com/TIGER-AI-Lab/MMLU-Pro/blob/47b9891aacb8bd7cda29d5c5ba17b9434dd333bc/evaluate_from_local.py#L17. This length was determined after comprehensive consideration of the 5-shot examples plus the prompt length. This context length should provide a good balance between performance and resource utilization for most benchmarking scenarios. I hope this helps you.

**Comment by ubergarm** [comment]
Super, I can work with 4096 context size. Thanks for pointing me in the right direction!
