### ISSUE TITLE
Add Gemini-1.5-Flash-002 and -Pro-002

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#25]
Google announced two new models: [Updated production-ready Gemini models, reduced 1.5 Pro pricing, increased rate limits, and more](https://developers.googleblog.com/en/updated-production-ready-gemini-models-reduced-15-pro-pricing-increased-rate-limits-and-more/)

- Gemini-1.5-Pro-002
- Gemini-1.5-Flash-002

Their self-reported scores are 67.3% for Flash and 75.8% for Pro. If correct, that would mean the new Pro model is 3rd on the leaderboard, and Flash is 11th.

Adding them to the leaderboard, preferably validated and per category, would be awesome!

**Comment by Wyyyb** [comment]
Thank you for your suggestion. We have now updated Gemini-1.5-Flash-002 and -Pro-002 on our leaderboard.
