### ISSUE TITLE
Add Ministral 3B and 8B

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#34]
Ministral 3B and 8B are SOTA edge models by Mistral AI: https://mistral.ai/news/ministraux/

It would be great to have them on the leaderboard!

**Comment by Wyyyb** [comment]
FYI, the 8B model has been updated in the leaderboard. The 3B model's overall accuracy is only around 10%, which doesn't exceed the random interval, so it hasn't been added to the leaderboard.
