### ISSUE TITLE
New model | Yi - Lightning

### ISSUE THREAD

**Issue by NSbuilder** [TIGER-AI-Lab/MMLU-Pro#36]
Seems like a new chinese SOTA MoE model. The successor of yi-large from 01.AI

https://x.com/Senseye_Winning/status/1845777940338143586

Top performance on lmarena.ai ( especially math and coding, besides sonnet 3.5).

Seems to beat Qwen 2.5 72B

Glm-4-plus and Yi lightning-lite are also new and impressive.

**Comment by wenhuchen** [comment]
Added already to the leaderboard. Thanks for the suggestion.
