### ISSUE TITLE
Add SmolLM2 1.7B

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#38]
SmolLM2 1.7B claims an impressive 19.4 MMLU-Pro score. Is would be great if it could be verified and added to the leaderboard.

https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B

**Comment by Wyyyb** [comment]
Thanks for your suggestion. We have tested SmolLM2 series models and added them to the leaderboard.
