### ISSUE TITLE
Which DeepSeek-Coder-V2?

### ISSUE THREAD

**Issue by billbradley** [TIGER-AI-Lab/MMLU-Pro#39]
The evaluation includes results for the LLM DeepSeek-Coder-V2. [Examining DeepSeek's GitHub repo](https://github.com/deepseek-ai/DeepSeek-Coder-V2) suggests that there are two possible models this could refer to: a 16B and a 236B parameter model.  Which one was used in the evaluation?

**Comment by wenhuchen** [comment]
We have included both of them. You can refer to the leaderboard for details.
