### ISSUE TITLE
Add Claude 3.5 Haiku

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#42]
Anthropic just released Claude 3.5 Haiku, I’m very curious how they score!

They claim 65.0% overall.

**Comment by Wyyyb** [comment]
Thanks, we have added its evaluation result to our leaderboard and the model output into our git repo.

**Comment by EwoutH** [comment]
Thanks!

it’s great that you guys do independent verification, because your measured 	
62.1% is noticeably lower than the 65.0% that Anthropic claimed.
