### ISSUE TITLE
Model requests - Gemini 2 27b, Claude 3 Haiku, Mixtral 8x22b

### ISSUE THREAD

**Issue by johns2s** [TIGER-AI-Lab/MMLU-Pro#45]
Can you test Gemma 2 27b-it? It would be interesting to see it compared to the already-tested 9b version and 1.5 Flash, which seems to be a similar size.

Similarly, now that 3.5 Haiku is on the leaderboard I’d like to see 3.0 Haiku’s performance, especially since it isn’t being deprecated.

And finally - Mixtral 8x22b. The MMLU Pro score listed on HuggingFace’s Open Leaderboard is under 40%. Given even 8x7b scored higher on your own tests, I’m not sure how accurate that result is.

**Comment by Wyyyb** [comment]
Thank you for your interest. We have already updated our leaderboard with the test results for Gemma 2 27b-it, Mixtral 8x22b, and Claude 3 haiku. Regarding the score differences you noticed on HuggingFace's Open Leaderboard, it's important to note that they apply a normalization process to all benchmark scores to account for random guess baselines. This normalization process is detailed in their documentation: https://huggingface.co/docs/leaderboards/open_llm_leaderboard/normalization 
This may explain the apparent discrepancy you observed in the Mixtral 8x22b MMLU Pro scores between different leaderboards.
