### ISSUE TITLE
Why not use ChatCompletion instead of Completion?

### ISSUE THREAD

**Issue by NagisaZj** [TIGER-AI-Lab/MMLU-Pro#48]
Hi, I found in your code that even for instruction-tuned models like Llama 3 8B Instruct, the Completion method is used for evaluation. I ould like to know that why not use the ChatCompletion method as these methods are specifically tuned for chat completion? Thank you very much.

**Comment by wenhuchen** [comment]
ChatCompletion and Completion are differing only in the prompt. It won't yield much difference.
