### ISSUE TITLE
Add Llama 3.3 70B

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#52]
Meta claims it’s on-par with 3.1 405B.

- https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct

**Comment by johns2s** [comment]
I tried to run the benchmark on Llama 3.3 on my own, using Hyperbolic through OpenRouter. Unfortunately some of the API responses failed over the long time the process was running, but I was able to get what appear to be full results for a couple of categories, and they look really impressive:

| Models | Data Source | Overall | Biology | Business | Chemistry | Law | Psychology |
|---------|--------------|----------|----------|-----------|-----------|------|------------|
| Llama-3.1-70B-Instruct | TIGER-Lab | 62.84% | 81.17% | 66.41% | 59.10% | 46.96% | 75.56% |
| Llama-3.3-70B-Instruct | Me/Hyperbolic | - | 85.50% | 75.79% | 69.42% | 52.13% | 78.46% |

**Comment by Wyyyb** [comment]
We have added it.
