### ISSUE TITLE
Add LG EXAONE-3.5 models (2.4B, 7.8B and 32B)

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#54]
- Link: [https://huggingface.co/collections/LGAI-EXAONE/exaone-35-674d0e1bb3dcd2ab6f39dbb4](https://huggingface.co/collections/LGAI-EXAONE/exaone-35-674d0e1bb3dcd2ab6f39dbb4)
- Technical Report: [https://arxiv.org/abs/2412.04862](https://arxiv.org/abs/2412.04862)
- Blog: [https://www.lgresearch.ai/blog/view?seq=507](https://www.lgresearch.ai/blog/view?seq=507)
- GitHub: [https://github.com/LG-AI-EXAONE/EXAONE-3.5](https://github.com/LG-AI-EXAONE/EXAONE-3.5)

**Comment by wenhuchen** [comment]
We will add them gradually

**Comment by Wyyyb** [comment]
We have added EXAONE-3.5-2.4B-Instruct, EXAONE-3.5-7.8B-Instruct, and EXAONE-3.5-32B-Instruct to our leaderboard.

**Comment by EwoutH** [comment]
Thanks, really appreciated!
