### ISSUE TITLE
Add Gemini 2.0 Flash

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#56]
- Blog: https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/
- Docs: https://ai.google.dev/gemini-api/docs/models/gemini-v2
- Vertex AI docs: https://cloud.google.com/vertex-ai/generative-ai/docs/gemini-v2

**Comment by Wyyyb** [comment]
added

**Comment by EwoutH** [comment]
Thanks! 76.2% is extremely impressive for such a fast and cheap model
