### ISSUE TITLE
Duplicates in test split

### ISSUE THREAD

**Issue by Pupy101** [TIGER-AI-Lab/MMLU-Pro#6]
Hello, can you help me? There are 159 questions with duplicates in the test part. Here is the code to find duplicates:

```python
from collections import defaultdict
import datasets

test = datasets.load_dataset("TIGER-Lab/MMLU-Pro", split="test")

mapping = defaultdict(int)

for item in test:
    mapping[(item["category"], item["question"], "".join(item["options"]), item["answer"])] += 1

count_doubles = 0
for (category, question, *_), count in mapping.items():
    if count > 1:
        print(category, repr(question))
        count_doubles += 1
print(count_doubles)
```

**Comment by Wyyyb** [comment]
Thank you for pointing out the duplicates. We have addressed this matter by removing the duplicate entries. Please pull the latest version of the dataset from Hugging Face to get the updated and deduplicated data.
