### ISSUE TITLE
Add IBM Granite 3.1

### ISSUE THREAD

**Issue by EwoutH** [TIGER-AI-Lab/MMLU-Pro#60]
IBM just released their Granite 3.1 models, a series of language models with 128K context length trained by IBM licensed under Apache 2.0 license.
- https://huggingface.co/collections/ibm-granite/granite-31-language-models-6751dbbf2f3389bec5c6f02d

**Comment by Wyyyb** [comment]
Thanks for the suggestion. We have added the test results of 8 IBM Granite 3.1 series models to the leaderboard.

**Comment by EwoutH** [comment]
Awesome, thanks!
